# Generated by Django 2.2 on 2021-01-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=400)),
                ('color', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
